weapons_reach:
  Magnum: 20
  Cowboy Gun: 20

weapons_init_ammo:
  Magnum: 6
  Cowboy Gun: 6

player_falling_speed: 2
player_jumping_height: 3
armor_strength: 1

weapon_spawn_sites:
  - [30, 10]
  - [15, 10]

player_spawn_sites:
  - [20, 30]
  - [30, 30]
  - [25, 30]

rows_map: 50
columns_map: 50
explosion_counter: 10
explosion_range: 5
rounds_per_cycle: 5
bullet_size: 2
mapId:
  - background
  - playerA
  - playerB
  - playerC
  - playerD
  - floor
  - wall
  - trail
  - bullet
  - ray
  - shotgun pellet
  - bananaProjectile
  - grenadeProjectile
  - box
  - brokenBox
  - armor
  - helmet
