player_falling_speed: 2
player_jumping_height: 6
armor_strength: 1

explosion_counter: 120
explosion_range: 2
stun_duration: 10
rounds_per_cycle: 3
bullet_size: 2
mapId:
  - background # 0
  - playerA # 1
  - playerB # 2
  - playerC # 3
  - playerD # 4
  - floor # 5
  - wall # 6
  - trail # 7
  - bullet # 8
  - ray # 9
  - shotgun pellet # 10
  - bananaProjectile # 11
  - grenadeProjectile # 12
  - box # 13
  - brokenBox # 14
  - armor # 15
  - helmet # 16

