weapons:
  magnum:
    reach: 40
    speed: 3
    deviation: 40
    ammo: 6
  ak47:
    reach: 26
    speed: 3
    deviation: 12
    ammo: 300
  duel:
    reach: 12
    speed: 3
    deviation: 12
    ammo: 1
  cowboy:
    reach: 40
    speed: 3
    deviation: 24
    ammo: 6
  shotgun:
    reach: 14
    speed: 3
    deviation: 1
    ammo: 2
    bullets_per_shot: 6
  sniper:
    reach: 128
    speed: 5
    ammo: 3
    deviation: 128
  pewpew:
    reach: 70
    speed: 3
    ammo: 12
    deviation: 12
