weapons:
  magnum:
    reach: 40
    speed: 6
    deviation: 40
    ammo: 6
  ak47:
    reach: 26
    speed: 6
    deviation: 12
    ammo: 30
  duel:
    reach: 12
    speed: 3
    deviation: 12
    ammo: 1
  cowboy:
    reach: 40
    speed: 6
    deviation: 24
    ammo: 6
